export const ADD = 'eventTypes/ADD'
export const ADD_SUCCESS = 'eventTypes/ADD_SUCCESS'
export const ADD_FAILURE = 'eventTypes/ADD_FAILURE'
export const FETCH = 'eventTypes/FETCH'
export const FETCH_SUCCESS = 'eventTypes/FETCH_SUCCESS'
export const FETCH_FAILURE = 'eventTypes/FETCH_FAILURE'
