export const ADD = 'notifications/ADD'
export const ADD_SUCCESS = 'notifications/ADD_SUCCESS'
export const ADD_FAILURE = 'notifications/ADD_FAILURE'
export const FETCH = 'notifications/FETCH'
export const FETCH_SUCCESS = 'notifications/FETCH_SUCCESS'
export const FETCH_FAILURE = 'notifications/FETCH_FAILURE'
