export const ADD = 'tenants/ADD'
export const ADD_SUCCESS = 'tenants/ADD_SUCCESS'
export const ADD_FAILURE = 'tenants/ADD_FAILURE'
export const FETCH = 'tenants/FETCH'
export const FETCH_SUCCESS = 'tenants/FETCH_SUCCESS'
export const FETCH_FAILURE = 'tenants/FETCH_FAILURE'
